### ISSUE TITLE
checkMetricsMarkdown fails on CI, but passes locally

### ISSUE THREAD

**Issue by iamdanfox** [palantir/metric-schema#338]
Reported by @sfackler in #dev-foundry-infra

https://circle.p.b/gh/v/a/27079

```
metrics.md is out of date, please run `./gradlew generateMetricsMarkdown` or `./gradlew --write-locks` to update it.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:823)
	at com.palantir.metric.schema.gradle.CheckMetricMarkdownTask.check(CheckMetricMarkdownTask.java:95)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:104)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTask
```

gradle-6.7-20200901220118+0000-bin.zip

**Comment by wenhoujx** [comment]
i think it's using the old cache. 
with cache 
```
circleci@0af36466ec74:~/project$ ./gradlew checkMetricsMarkdown

> Task :redacted-my-project-integration-engine:createMetricsManifest FROM-CACHE
> Task :redacted-my-project-datagen:createMetricsManifest FROM-CACHE

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':redacted-my-project:checkMetricsMarkdown'.
> metrics.md is out of date, please run `./gradlew checkMetricsMarkdown` or `./gradlew --write-locks` to update it.

BUILD FAILED in 34s
8 actionable tasks: 1 executed, 2 from cache, 5 up-to-date

Publishing build scan...
https://gradle.palantir.build/s/zag2u75zvwdts
```
without cache 
```
circleci@0af36466ec74:~/project$ ./gradlew checkMetricsMarkdown --rerun-tasks
> Task :redacted-my-project-client:compileMetricSchema
> Task :redacted-my-project-datagen:compileMetricSchema NO-SOURCE
> Task :redacted-my-project:compileMetricSchema
> Task :redacted-my-project-api-shared:compileMetricSchema
> Task :redacted-my-project-integration-engine:compileMetricSchema
> Task :redacted-my-project-datagen:createMetricsManifest
> Task :redacted-my-project-datagen:checkMetricsMarkdown
> Task :redacted-my-project:createMetricsManifest
> Task :redacted-my-project:checkMetricsMarkdown
> Task :redacted-my-project-integration-engine:createMetricsManifest
> Task :redacted-my-project-integration-engine:checkMetricsMarkdown


BUILD SUCCESSFUL in 8s
10 actionable tasks: 10 executed

Publishing build scan...
https://gradle.palantir.build/s/u4h7sdq2tkm6s
```
